name: Tests

on:
  push:
    branches:
      - master

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v3
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ secrets.CACHE_VERSION }}-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-
    - uses: jeffreytse/jekyll-deploy-action@v0.4.0
      with:
        provider: 'github'
        token: ${{ secrets.GITHUB_TOKEN }}
        jekyll_src: './'
        jekyll_baseurl: '/tfda6'
